services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user_teste
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistência dos dados do banco

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db 
    environment:
      DB_HOST: "db"
      DB_USER: "user_teste"
      DB_PASSWORD: "password"
      DB_PORT: "5432"
      DB_NAME: "teste"
    volumes:
      - .:/app # Volume para o código do app

volumes:
  pgdata:
